services:
  ros:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    user: "efliao:efliao"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/ros2_ws/src
    command: >
      ros2 run turtlesim turtlesim_node
