services:
  ros2:
    container_name: ros2
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    user: "efliao:efliao"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/ros2_ws
